/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Roundcube: THREE.Mesh;
    Roundcube003: THREE.Mesh;
    Roundcube005: THREE.Mesh;
    Roundcube011: THREE.Mesh;
    Roundcube013: THREE.Mesh;
    Roundcube017: THREE.Mesh;
    Roundcube021: THREE.Mesh;
    Roundcube025: THREE.Mesh;
    Roundcube029: THREE.Mesh;
    Roundcube033: THREE.Mesh;
    Roundcube037: THREE.Mesh;
    Roundcube042: THREE.Mesh;
    Roundcube045: THREE.Mesh;
    Roundcube001: THREE.Mesh;
    Roundcube002: THREE.Mesh;
    Roundcube004: THREE.Mesh;
    Roundcube006: THREE.Mesh;
    Roundcube007: THREE.Mesh;
    Roundcube008: THREE.Mesh;
    Roundcube009: THREE.Mesh;
    Roundcube010: THREE.Mesh;
    Roundcube012: THREE.Mesh;
    Roundcube014: THREE.Mesh;
    Roundcube015: THREE.Mesh;
    Roundcube016: THREE.Mesh;
    Roundcube018: THREE.Mesh;
    Roundcube019: THREE.Mesh;
    Roundcube020: THREE.Mesh;
    Roundcube022: THREE.Mesh;
    Roundcube023: THREE.Mesh;
    Roundcube024: THREE.Mesh;
    Roundcube026: THREE.Mesh;
    Roundcube027: THREE.Mesh;
    Roundcube028: THREE.Mesh;
    Roundcube030: THREE.Mesh;
    Roundcube031: THREE.Mesh;
    Roundcube032: THREE.Mesh;
    Roundcube034: THREE.Mesh;
    Roundcube035: THREE.Mesh;
    Roundcube036: THREE.Mesh;
    Roundcube038: THREE.Mesh;
    Roundcube039: THREE.Mesh;
    Roundcube040: THREE.Mesh;
    Roundcube041: THREE.Mesh;
    Roundcube043: THREE.Mesh;
    Roundcube044: THREE.Mesh;
    Roundcube046: THREE.Mesh;
    Roundcube047: THREE.Mesh;
    Roundcube048: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | 'Roundcube'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Roundcube.001Action'
  | 'Empty'
  | 'Roundcube.001Action'
  | 'Empty.001'
  | 'Roundcube.001Action'
  | 'Empty.002'
  | 'Empty.003'
  | 'Roundcube.001Action'
  | 'Empty.004'
  | 'Empty.005'
  | 'Roundcube.001Action'
  | 'Empty.006'
  | 'Roundcube.001Action'
  | 'Empty.007'
  | 'Roundcube.001Action'
  | 'Empty.008'
  | 'Roundcube.001Action'
  | 'Empty.009'
  | 'Roundcube.001Action'
  | 'Empty.010'
  | 'Empty.011'
  | 'Roundcube.001Action'
  | 'Empty.012'
  | 'Empty.013'
  | 'Roundcube.001Action'
  | 'Empty.014'
  | 'Roundcube.001Action'
  | 'Empty.015'
  | 'Roundcube.001Action'
  | 'Empty.016'
  | 'Empty.017'
  | 'Roundcube.001Action'
  | 'Empty.018'
  | 'Roundcube.001Action'
  | 'Empty.019'
  | 'Roundcube.001Action'
  | 'Empty.020'
  | 'Empty.021'
  | 'Roundcube.001Action'
  | 'Empty.022'
  | 'Roundcube.001Action'
  | 'Empty.023'
  | 'Roundcube.001Action'
  | 'Empty.024'
  | 'Empty.025'
  | 'Roundcube.001Action'
  | 'Empty.026'
  | 'Roundcube.001Action'
  | 'Empty.027'
  | 'Roundcube.001Action'
  | 'Empty.028'
  | 'Empty.029'
  | 'Roundcube.001Action'
  | 'Empty.030'
  | 'Roundcube.001Action'
  | 'Empty.031'
  | 'Roundcube.001Action'
  | 'Empty.032'
  | 'Empty.033'
  | 'Roundcube.001Action'
  | 'Empty.034'
  | 'Roundcube.001Action'
  | 'Empty.035'
  | 'Roundcube.001Action'
  | 'Empty.036'
  | 'Empty.037'
  | 'Roundcube.001Action'
  | 'Empty.038'
  | 'Roundcube.001Action'
  | 'Empty.039'
  | 'Roundcube.001Action'
  | 'Empty.040'
  | 'Roundcube.001Action'
  | 'Empty.041'
  | 'Empty.042'
  | 'Roundcube.001Action'
  | 'Empty.043'
  | 'Roundcube.001Action'
  | 'Empty.044'
  | 'Empty.045'
  | 'Roundcube.001Action'
  | 'Empty.046'
  | 'Roundcube.001Action'
  | 'Empty.047'
  | 'Roundcube.001Action';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

const stringArray: string[] = [
  'Roundcube',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Roundcube.001Action',
  'Empty',
  'Roundcube.001Action',
  'Empty.001',
  'Roundcube.001Action',
  'Empty.002',
  'Empty.003',
  'Roundcube.001Action',
  'Empty.004',
  'Empty.005',
  'Roundcube.001Action',
  'Empty.006',
  'Roundcube.001Action',
  'Empty.007',
  'Roundcube.001Action',
  'Empty.008',
  'Roundcube.001Action',
  'Empty.009',
  'Roundcube.001Action',
  'Empty.010',
  'Empty.011',
  'Roundcube.001Action',
  'Empty.012',
  'Empty.013',
  'Roundcube.001Action',
  'Empty.014',
  'Roundcube.001Action',
  'Empty.015',
  'Roundcube.001Action',
  'Empty.016',
  'Empty.017',
  'Roundcube.001Action',
  'Empty.018',
  'Roundcube.001Action',
  'Empty.019',
  'Roundcube.001Action',
  'Empty.020',
  'Empty.021',
  'Roundcube.001Action',
  'Empty.022',
  'Roundcube.001Action',
  'Empty.023',
  'Roundcube.001Action',
  'Empty.024',
  'Empty.025',
  'Roundcube.001Action',
  'Empty.026',
  'Roundcube.001Action',
  'Empty.027',
  'Roundcube.001Action',
  'Empty.028',
  'Empty.029',
  'Roundcube.001Action',
  'Empty.030',
  'Roundcube.001Action',
  'Empty.031',
  'Roundcube.001Action',
  'Empty.032',
  'Empty.033',
  'Roundcube.001Action',
  'Empty.034',
  'Roundcube.001Action',
  'Empty.035',
  'Roundcube.001Action',
  'Empty.036',
  'Empty.037',
  'Roundcube.001Action',
  'Empty.038',
  'Roundcube.001Action',
  'Empty.039',
  'Roundcube.001Action',
  'Empty.040',
  'Roundcube.001Action',
  'Empty.041',
  'Empty.042',
  'Roundcube.001Action',
  'Empty.043',
  'Roundcube.001Action',
  'Empty.044',
  'Empty.045',
  'Roundcube.001Action',
  'Empty.046',
  'Roundcube.001Action',
  'Empty.047',
  'Roundcube.001Action',
];

export function SunModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF('/sun.gltf') as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);

  // useEffect(() => {
  //   stringArray.forEach((item) => {
  //     console.log(item);
  //     actions[item]
  //       ?.reset()
  //       .setEffectiveTimeScale(1)
  //       .setEffectiveWeight(1)
  //       .fadeIn(0.5)
  //       .play().loop;
  //   });
  // }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='Roundcube'
          castShadow
          receiveShadow
          geometry={nodes.Roundcube.geometry}
          material={materials['Material.002']}
          position={[0, 0, 0]}
          scale={0.719}
          // scale={0.1}
          userData={{ name: 'Roundcube' }}
        >
          <mesh
            name='Roundcube003'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube003.geometry}
            material={materials['Material.002']}
            position={[0, 0, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.003' }}
          />
          <mesh
            name='Roundcube005'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube005.geometry}
            material={materials['Material.002']}
            position={[0, 0, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.005' }}
          />
          <mesh
            name='Roundcube011'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube011.geometry}
            material={materials['Material.002']}
            // position={[0, 1.456, 0]}
            position={[0, 0, 0]}
            scale={0.1}
          />
          <mesh
            name='Roundcube013'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube013.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
          />
          <mesh
            name='Roundcube017'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube017.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.017' }}
          />
          <mesh
            name='Roundcube021'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube021.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.021' }}
          />
          <mesh
            name='Roundcube025'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube025.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.025' }}
          />
          <mesh
            name='Roundcube029'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube029.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.029' }}
          />
          <mesh
            name='Roundcube033'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube033.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.033' }}
          />
          <mesh
            name='Roundcube037'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube037.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.037' }}
          />
          <mesh
            name='Roundcube042'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube042.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.042' }}
          />
          <mesh
            name='Roundcube045'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube045.geometry}
            material={materials['Material.002']}
            position={[0, 1.456, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.045' }}
          />
        </mesh>
        <group name='Empty' userData={{ name: 'Empty' }}>
          <mesh
            name='Roundcube001'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube001.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.001' }}
          />
        </group>
        <group name='Empty001' userData={{ name: 'Empty.001' }}>
          <mesh
            name='Roundcube002'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube002.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.002' }}
          />
        </group>
        <group name='Empty002' userData={{ name: 'Empty.002' }} />
        <group name='Empty003' userData={{ name: 'Empty.003' }}>
          <mesh
            name='Roundcube004'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube004.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.004' }}
          />
        </group>
        <group
          name='Empty004'
          rotation={[0, 0, Math.PI / 6]}
          userData={{ name: 'Empty.004' }}
        />
        <group
          name='Empty005'
          rotation={[0, 0, Math.PI / 6]}
          userData={{ name: 'Empty.005' }}
        >
          <mesh
            name='Roundcube006'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube006.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.006' }}
          />
        </group>
        <group
          name='Empty006'
          rotation={[0, 0, Math.PI / 6]}
          userData={{ name: 'Empty.006' }}
        >
          <mesh
            name='Roundcube007'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube007.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.007' }}
          />
        </group>
        <group
          name='Empty007'
          rotation={[0, 0, Math.PI / 6]}
          userData={{ name: 'Empty.007' }}
        >
          <mesh
            name='Roundcube008'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube008.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.008' }}
          />
        </group>
        <group
          name='Empty008'
          rotation={[0, 0, Math.PI / 3]}
          userData={{ name: 'Empty.008' }}
        >
          <mesh
            name='Roundcube009'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube009.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.009' }}
          />
        </group>
        <group
          name='Empty009'
          rotation={[0, 0, Math.PI / 3]}
          userData={{ name: 'Empty.009' }}
        >
          <mesh
            name='Roundcube010'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube010.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.010' }}
          />
        </group>
        <group
          name='Empty010'
          rotation={[0, 0, Math.PI / 3]}
          userData={{ name: 'Empty.010' }}
        />
        <group
          name='Empty011'
          rotation={[0, 0, Math.PI / 3]}
          userData={{ name: 'Empty.011' }}
        >
          <mesh
            name='Roundcube012'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube012.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.012' }}
          />
        </group>
        <group
          name='Empty012'
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'Empty.012' }}
        />
        <group
          name='Empty013'
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'Empty.013' }}
        >
          <mesh
            name='Roundcube014'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube014.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.014' }}
          />
        </group>
        <group
          name='Empty014'
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'Empty.014' }}
        >
          <mesh
            name='Roundcube015'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube015.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.015' }}
          />
        </group>
        <group
          name='Empty015'
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: 'Empty.015' }}
        >
          <mesh
            name='Roundcube016'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube016.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.016' }}
          />
        </group>
        <group
          name='Empty016'
          rotation={[0, 0, 2.094]}
          userData={{ name: 'Empty.016' }}
        />
        <group
          name='Empty017'
          rotation={[0, 0, 2.094]}
          userData={{ name: 'Empty.017' }}
        >
          <mesh
            name='Roundcube018'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube018.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.018' }}
          />
        </group>
        <group
          name='Empty018'
          rotation={[0, 0, 2.094]}
          userData={{ name: 'Empty.018' }}
        >
          <mesh
            name='Roundcube019'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube019.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.019' }}
          />
        </group>
        <group
          name='Empty019'
          rotation={[0, 0, 2.094]}
          userData={{ name: 'Empty.019' }}
        >
          <mesh
            name='Roundcube020'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube020.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.020' }}
          />
        </group>
        <group
          name='Empty020'
          rotation={[0, 0, 2.618]}
          userData={{ name: 'Empty.020' }}
        />
        <group
          name='Empty021'
          rotation={[0, 0, 2.618]}
          userData={{ name: 'Empty.021' }}
        >
          <mesh
            name='Roundcube022'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube022.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.022' }}
          />
        </group>
        <group
          name='Empty022'
          rotation={[0, 0, 2.618]}
          userData={{ name: 'Empty.022' }}
        >
          <mesh
            name='Roundcube023'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube023.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.023' }}
          />
        </group>
        <group
          name='Empty023'
          rotation={[0, 0, 2.618]}
          userData={{ name: 'Empty.023' }}
        >
          <mesh
            name='Roundcube024'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube024.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.024' }}
          />
        </group>
        <group
          name='Empty024'
          rotation={[0, 0, Math.PI]}
          userData={{ name: 'Empty.024' }}
        />
        <group
          name='Empty025'
          rotation={[0, 0, Math.PI]}
          userData={{ name: 'Empty.025' }}
        >
          <mesh
            name='Roundcube026'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube026.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.026' }}
          />
        </group>
        <group
          name='Empty026'
          rotation={[0, 0, Math.PI]}
          userData={{ name: 'Empty.026' }}
        >
          <mesh
            name='Roundcube027'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube027.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.027' }}
          />
        </group>
        <group
          name='Empty027'
          rotation={[0, 0, Math.PI]}
          userData={{ name: 'Empty.027' }}
        >
          <mesh
            name='Roundcube028'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube028.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.028' }}
          />
        </group>
        <group
          name='Empty028'
          rotation={[0, 0, -2.618]}
          userData={{ name: 'Empty.028' }}
        />
        <group
          name='Empty029'
          rotation={[0, 0, -2.618]}
          userData={{ name: 'Empty.029' }}
        >
          <mesh
            name='Roundcube030'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube030.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.030' }}
          />
        </group>
        <group
          name='Empty030'
          rotation={[0, 0, -2.618]}
          userData={{ name: 'Empty.030' }}
        >
          <mesh
            name='Roundcube031'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube031.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.031' }}
          />
        </group>
        <group
          name='Empty031'
          rotation={[0, 0, -2.618]}
          userData={{ name: 'Empty.031' }}
        >
          <mesh
            name='Roundcube032'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube032.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.032' }}
          />
        </group>
        <group
          name='Empty032'
          rotation={[0, 0, -2.094]}
          userData={{ name: 'Empty.032' }}
        />
        <group
          name='Empty033'
          rotation={[0, 0, -2.094]}
          userData={{ name: 'Empty.033' }}
        >
          <mesh
            name='Roundcube034'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube034.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.034' }}
          />
        </group>
        <group
          name='Empty034'
          rotation={[0, 0, -2.094]}
          userData={{ name: 'Empty.034' }}
        >
          <mesh
            name='Roundcube035'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube035.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.035' }}
          />
        </group>
        <group
          name='Empty035'
          rotation={[0, 0, -2.094]}
          userData={{ name: 'Empty.035' }}
        >
          <mesh
            name='Roundcube036'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube036.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.036' }}
          />
        </group>
        <group
          name='Empty036'
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: 'Empty.036' }}
        />
        <group
          name='Empty037'
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: 'Empty.037' }}
        >
          <mesh
            name='Roundcube038'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube038.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.038' }}
          />
        </group>
        <group
          name='Empty038'
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: 'Empty.038' }}
        >
          <mesh
            name='Roundcube039'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube039.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.039' }}
          />
        </group>
        <group
          name='Empty039'
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: 'Empty.039' }}
        >
          <mesh
            name='Roundcube040'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube040.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.040' }}
          />
        </group>
        <group
          name='Empty040'
          rotation={[0, 0, -Math.PI / 3]}
          userData={{ name: 'Empty.040' }}
        >
          <mesh
            name='Roundcube041'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube041.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.041' }}
          />
        </group>
        <group
          name='Empty041'
          rotation={[0, 0, -Math.PI / 3]}
          userData={{ name: 'Empty.041' }}
        />
        <group
          name='Empty042'
          rotation={[0, 0, -Math.PI / 3]}
          userData={{ name: 'Empty.042' }}
        >
          <mesh
            name='Roundcube043'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube043.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.043' }}
          />
        </group>
        <group
          name='Empty043'
          rotation={[0, 0, -Math.PI / 3]}
          userData={{ name: 'Empty.043' }}
        >
          <mesh
            name='Roundcube044'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube044.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.044' }}
          />
        </group>
        <group
          name='Empty044'
          rotation={[0, 0, -Math.PI / 6]}
          userData={{ name: 'Empty.044' }}
        />
        <group
          name='Empty045'
          rotation={[0, 0, -Math.PI / 6]}
          userData={{ name: 'Empty.045' }}
        >
          <mesh
            name='Roundcube046'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube046.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.046' }}
          />
        </group>
        <group
          name='Empty046'
          rotation={[0, 0, -Math.PI / 6]}
          userData={{ name: 'Empty.046' }}
        >
          <mesh
            name='Roundcube047'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube047.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            // scale={0.1}
            scale={0.1}
            userData={{ name: 'Roundcube.047' }}
          />
        </group>
        <group
          name='Empty047'
          rotation={[0, 0, -Math.PI / 6]}
          scale={0.1}
          userData={{ name: 'Empty.047' }}
        >
          <mesh
            name='Roundcube048'
            castShadow
            receiveShadow
            geometry={nodes.Roundcube048.geometry}
            material={materials['Material.002']}
            position={[0, 1.047, 0]}
            scale={0.1}
            userData={{ name: 'Roundcube.048' }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/sun2.gltf');
